.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "HEXCHAT\-RESET" "1" "January 2020" "anon-apps-config" "anon-apps-config Manual"
.SH "NAME"
\fBhexchat\-reset\fR \- HexChat New Identity
.SH "SYNOPSIS"
\fBhexchat\-reset\fR
.SH "DESCRIPTION"
Kills running \fBHexChat\fR(1) processes, moves your \fB/home/user/\.config/hexchat folder to\fR/home/user/hexchat_(current date and time)\fBas a backup\. Then creates a fresh HexChat profile folder\fR/home/user/\.config/hexchat`, with privacy hardened defaults, which come with Whonix\.
.P
Be sure to change your Tor circuit before reconnecting to IRC!
.SH "EXIT CODES"
0 Success
.P
1 Error
.SH "EXAMPLE"
\fBhexchat\-reset\fR
.SH "NOTES"
Do not run as root!
.SH "PORTING"
This script is currently only tested in Whonix\. It could be easily made to work in Tails or on any Linux\.
.SH "WWW"
https://www\.whonix\.org/wiki/HexChat
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
