#!/bin/sh

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category apps
#### description
## Add <code>/usr/share/anon-apps-config/</code> to
## <code>XDG_CONFIG_DIRS</code> environment variable.
#### meta end

if [ -z "$XDG_CONFIG_DIRS" ]; then
   XDG_CONFIG_DIRS=/etc/xdg
fi
export XDG_CONFIG_DIRS=/usr/share/anon-apps-config/:$XDG_CONFIG_DIRS

if [ -z "$XDG_DATA_DIRS" ]; then
   XDG_DATA_DIRS=/usr/local/share/:/usr/share/
fi
export XDG_DATA_DIRS=/usr/share/anon-apps-config/share/:$XDG_DATA_DIRS
